### ISSUE TITLE
Failure during fastq to fasta conversion 

### ISSUE THREAD

**Issue by sckstraub** [V-Z/sondovac#2]
I ran the pipeline with the following command: 

sondovac_part_a.sh -n -f transcriptome.fasta -c plastome.fasta -m mitochondriome.fasta -t R1.fastq -q R2.fastq -o sondovac_test

But there is a failure at the fastq to fasta conversion:

Converting FASTQ to FASTA. This may take longer time.
fastq_to_fasta: Invalid quality score value (char ',' ord 44 quality value -20) on line 28

Error! Conversion of FASTQ to FASTA failed. Aborting. Check if file
sondovac_test_combined_reads_no_cp_no_mt_reads.extendedFrags.fastq is correct.

In Phred+33, which was used for FLASH in the previous step, ',' is a valid quality score. I see no problems with the fastq file. Can you suggest a fix?

**Comment by V-Z** [comment]
I'm sorry You have problems running the pipeline. How did You install FASTX-Toolkit? Which version of this software do You have? If pre 0.0.13, please, upgrade to this version and try it again.

**Comment by sckstraub** [comment]
Our cluster administrator installs the programs, so I cannot answer your first question. The FASTX-Toolkit is version 0.0.13.2.

**Comment by V-Z** [comment]
Ah, thank You for finding my mistake in the documentation first. I always stated there that required version is 0.0.13, but in fact we were always using (and the script includes) version 0.0.14.
One colleague reported mi exactly same problem and in his case, the problem was in old version of FASTX-Toolkit.
I don't know how Your cluster is managed, but may I ask You to try with v. 0.0.14 from http://hannonlab.cshl.edu/fastx_toolkit/download.html or there referenced GitHub repository?

**Comment by sckstraub** [comment]
I updated FASTX-Toolkit, but now the pipeline fails at an earlier step. I checked all of the indicated files and do not see a problem with them.

Step 4 of the pipeline - combination of paired-end reads.

Combining paired-end reads

[FLASH] ERROR: Failed to open ".//scratch/straub/sondovac_results_2/sondovac_test_ref_2_combined_reads_no_cp_no_mt_reads.extendedFrags.fastq" for writing: No such file or directory
[FLASH] FLASH did not complete successfully; exiting with failure status (1)

Error! Combining paired-end reads failed. Aborting. Check if files
/scratch/straub/mitochondriome_non-interleaved.fasta, /scratch/straub/sondovac_results_2/sondovac_test_ref_2_genome_skim_data_no_cp_no_mt_reads_1.fq and /scratch/straub/sondovac_results_2/sondovac_test_ref_2_genome_skim_data_no_cp_no_mt_reads_2.fq are correct.

**Comment by V-Z** [comment]
Hm, can You, please, write versions of all software in use? It is listed in Table 2, https://github.com/V-Z/sondovac/blob/master/manual/sondovac_manual.pdf Newer versions then listed should be fine.

**Comment by V-Z** [comment]
One more idea, do You execute the command via qsub or some similar tool to submit it into the task queue? Could You post list of Your working directory? I'm wondering because path like ".//..." is wrong. And I don't see reason why it should be created by the script. FASTX is not involved in this step yet, so I don't see any reason to fail because of that change.
